[package]
name = "cppshift"
version = "0.1.0"
authors = ["Jérémy HERGAULT", "Enzo PASQUALINI"]
description = "CPP parser and transpiler"
repository = "https://github.com/worldline/cppshift"
edition = "2024"
license = "Apache-2.0"

[dependencies]
miette = { version = "7", features = ["fancy"] }
thiserror = "2"

[dev-dependencies]
tokio = { version = "1", features = ["macros"] }
reqwest = "0.12"
glob = "0.3"
